---
name: torus
director_uuid: CHANGE-ME

releases:
  - name: torus
    version: latest

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

instance_groups:
  - name: torusd
    instances: 1
    jobs:
      - name: torusd
        release: torus
    vm_type: default
    stemcell: default
    persistent_disk_type: default
    azs:
      - default
    networks:
      - name: default

properties: {}
